CREATE TABLE monitors (
    id VARCHAR(20) PRIMARY KEY,
    timeout SMALLINT NOT NULL,
    alert_email VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);